export default {
    "binds": {
        "n": "control selfie",
        "m": "control not selfie",
        "h": "hi! | hey ! | hey you! | hello...",
        "i": "it's doer 1 | it's me, doer 1 | doer 1 that's me",
        "f1": "control help",
        "f2": "control not help",
        "!": "welcome to a.goblin.life",
        "@": "these are keybinds",
        "#": "press ~ or enter then type ~ bind 3 to change this bind",
        "$": "press f1 to explore other commands",
        "%": "good luck, have fun",
        "^": "foobar",
        "*": "ja ja",
        "&": "no no",
        "f": "~ not pointerlock",
        "q": "~ toggle drop",
        "e": "~ toggle throw",
        "1": "~ use bag1",
        "2": "~ use bag2",
        "3": "~ use bag3",
        "4": "~ use bag4",
        "5": "~ use bag5",
        "6": "~ use bag6",
        "7": "~ use bag7",
        "8": "~ use bag8",
    },
    "vars": {

    },
    "selfie": false,
    avatar: {
        doer: "./vrm/doer.2.vrm",
        current: "./vrm/doer.2.vrm"
    },
    binds_icon: {
        "!": "🔥",
        "@": "🏴‍☠️",
        "#": "💕",
        "$": "🏜️",
        "%": "🌪️",
        "^": "🌈",
        "*": "🌊",
        "&": "🌋",
        9: "🌌",
        0: "🌍",
    },
    visible: true
}